using TokenObservability.Domain.Tenancy;

namespace TokenObservability.Domain.Ingestion;

public sealed record TelemetryEnvelopeRecord(
    string TelemetryEnvelopeId,
    CustomerOrganizationId CustomerOrganizationId,
    string HarnessSetupProfileId,
    ScopedIngestionCredentialId ScopedIngestionCredentialId,
    ProductUserId ProductUserId,
    string Harness,
    string SchemaVersion,
    string SignalType,
    string SourceEventName,
    DateTimeOffset? SourceEventTimestampUtc,
    DateTimeOffset ReceivedAtUtc,
    string? ConversationIdHash,
    string? TurnIdHash,
    string? SourceEventId,
    string? TraceIdHash,
    string? SpanIdHash,
    string? ModelName,
    string? HarnessVersion,
    string? SandboxSetting,
    string? ApprovalSetting,
    string ContentPolicyDecision,
    string ContentCaptureState,
    string RedactionState,
    IReadOnlyDictionary<string, string> RoutingDecision,
    string EvidenceState,
    string MetricState,
    string SourceEvidenceKind,
    string CorrelationId,
    string DedupeKeyHash,
    IReadOnlyDictionary<string, string> IngestionVersionMetadata);

public sealed record AgentSessionRecord(
    string AgentSessionId,
    CustomerOrganizationId CustomerOrganizationId,
    ProductUserId ProductUserId,
    string HarnessSetupProfileId,
    string Harness,
    string? ProviderSessionIdHash,
    DateTimeOffset? StartedAtUtc,
    DateTimeOffset? EndedAtUtc,
    string SessionStatus,
    string? Environment,
    string? SandboxSetting,
    string? ApprovalSetting,
    string RepositoryEvidenceState,
    string ContentCaptureSummary,
    string RecommendationStatus,
    IReadOnlyList<string> ModelNames,
    IReadOnlyList<string> SourceTelemetryEnvelopeIds,
    DateTimeOffset CreatedAtUtc,
    DateTimeOffset UpdatedAtUtc);

public sealed record CreateTelemetryEnvelopeRecordRequest(
    CustomerOrganizationId CustomerOrganizationId,
    string HarnessSetupProfileId,
    ScopedIngestionCredentialId ScopedIngestionCredentialId,
    ProductUserId ProductUserId,
    string Harness,
    string SchemaVersion,
    string SignalType,
    string SourceEventName,
    DateTimeOffset? SourceEventTimestampUtc,
    string? ConversationIdHash,
    string? TurnIdHash,
    string? SourceEventId,
    string? TraceIdHash,
    string? SpanIdHash,
    string? ModelName,
    string? HarnessVersion,
    string? SandboxSetting,
    string? ApprovalSetting,
    string RepositoryEvidenceState,
    string ContentPolicyDecision,
    string ContentCaptureState,
    string RedactionState,
    IReadOnlyDictionary<string, string> RoutingDecision,
    string EvidenceState,
    string MetricState,
    string SourceEvidenceKind,
    string CorrelationId,
    string DedupeKeyHash,
    IReadOnlyDictionary<string, string> IngestionVersionMetadata);
